POST http://localhost:3000/api/v1/task
Content-Type: application/json
{
    "name": "teste",
    "userName": "admin"    
}

####
PATCH  http://localhost:3000/api/v1/task/outra3
Content-Type: application/json
{    
    "userName": "admin",
    "newDescription": "descrição4"
}

###
GET  http://localhost:3000/api/v1/task
Content-Type: application/json

###
DELETE  http://localhost:3000/api/v1/task/outra3
Content-Type: application/json
